INSERT INTO roles (name, description) VALUES
('INSURED', 'Policyholder filing FNOL'),
('CALL_CENTER_AGENT', 'Customer service user handling FNOL calls'),
('SURVEYOR_DISPATCHER', 'Assigns surveyors to FNOLs'),
('LOSS_ADJUSTER_INTERNAL', 'Internal loss adjuster'),
('LOSS_ADJUSTER_EXTERNAL', 'External loss adjuster'),
('LOSS_ADJUSTER_EXTERNAL_ADMIN', 'Admin for external loss adjustors'),
('ASSESSOR', 'Assessor user'),
('ASSESSOR_MANAGER', 'Manages assessors'),
('ASSESSOR_SUPERVISOR', 'Supervises assessors'),
('CLAIMS_SLA_SUPERVISOR', 'Monitors SLA compliance'),
('CLAIMS_PAYMENT_OFFICER', 'Handles claims payments'),
('FINANCE_USER', 'Finance team user'),
('LEGAL_USER', 'Legal department user'),
('SIU_USER', 'Special Investigation Unit (fraud)'),
('GARAGE_USER', 'Garage/repair center user'),
('GARAGE_USER_NON_CONTRACTED', 'Non-contracted garage user'),
('PROCUREMENT_USER', 'Procurement officer'),
('PROCUREMENT_MANAGER', 'Senior procurement manager'),
('SUPPLIER_USER', 'General supplier'),
('SUPPLIER_WINDSHIELD', 'Windshield supplier'),
('SUPPLIER_ADMIN', 'Supplier/Vendor admin'),
('SYS_ADMIN', 'System administrator');
