


-- Generated by the database client.
CREATE TABLE address(
    id SERIAL NOT NULL,
    address_line1 varchar(255),
    address_line2 varchar(255),
    city varchar(255),
    country varchar(255),
    created_at date,
    latitude double precision,
    location_type varchar(255),
    longitude double precision,
    postal_code varchar(255),
    province varchar(255),
    updated_at date,
    PRIMARY KEY(id),
    CONSTRAINT address_location_type_check CHECK ((location_type)::text = ANY ((ARRAY['ACCIDENT_SITE'::character varying, 'INSURED_ADDRESS'::character varying, 'GARAGE'::character varying, 'BRANCH_OFFICE'::character varying, 'OTHER'::character varying])::text[]))
);




-- Generated by the database client.
CREATE TABLE claim(
    id SERIAL NOT NULL,
    claim_amount double precision,
    claim_date date,
    claim_number varchar(255),
    claim_severity varchar(255),
    claim_status varchar(255),
    date_reported date,
    incident_date date,
    location varchar(255),
    status varchar(255),
    address_id bigint,
    fnol_id bigint,
    policy_id bigint,
    surveyor_id bigint,
    PRIMARY KEY(id),
    CONSTRAINT fk3or9dmjgfq5pgjbbar9v7jk76 FOREIGN key(address_id) REFERENCES address(id),
    CONSTRAINT fk5vx1a6ddxavwks41w18auk4b6 FOREIGN key(fnol_id) REFERENCES fnol(id),
    CONSTRAINT fk576m2dixnoqkcdu0sh90742ug FOREIGN key(policy_id) REFERENCES policy(id),
    CONSTRAINT fkaqingufy9o3p3urt98yjvo8jt FOREIGN key(surveyor_id) REFERENCES surveyor(id),
    CONSTRAINT claim_claim_severity_check CHECK ((claim_severity)::text = ANY ((ARRAY['High'::character varying, 'Medium'::character varying, 'Low'::character varying])::text[])),
    CONSTRAINT claim_claim_status_check CHECK ((claim_status)::text = ANY ((ARRAY['REGISTERED'::character varying, 'UNDER_REVIEW'::character varying, 'APPROVAL_PENDING'::character varying, 'APPROVED'::character varying, 'WORK_IN_PROGRESS'::character varying, 'REJECTED'::character varying, 'PAID'::character varying, 'CLOSED'::character varying, 'REOPENED'::character varying])::text[])),
    CONSTRAINT claim_status_check CHECK ((status)::text = ANY ((ARRAY['REGISTERED'::character varying, 'UNDER_REVIEW'::character varying, 'APPROVAL_PENDING'::character varying, 'APPROVED'::character varying, 'WORK_IN_PROGRESS'::character varying, 'REJECTED'::character varying, 'PAID'::character varying, 'CLOSED'::character varying, 'REOPENED'::character varying])::text[]))
);


-- Generated by the database client.
CREATE TABLE fnol(
    id SERIAL NOT NULL,
    accident_date timestamp without time zone,
    description varchar(255),
    fnol_reference_no varchar(255),
    fnol_state varchar(255),
    incident_description varchar(255),
    severity varchar(255),
    updated_at date,
    accident_location_id bigint NOT NULL,
    policy_id bigint NOT NULL,
    surveyor_id bigint NOT NULL,
    vehicle_id bigint NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fktbn9cqjf5toxfmky3m01x1722 FOREIGN key(accident_location_id) REFERENCES address(id),
    CONSTRAINT fkq3vsnxjbk150qdm0nx64s7wui FOREIGN key(policy_id) REFERENCES policy(id),
    CONSTRAINT fkilw724wuxje0ksrokcpl5vu0v FOREIGN key(surveyor_id) REFERENCES surveyor(id),
    CONSTRAINT fk80us1o3e0n35apn072yardf2o FOREIGN key(vehicle_id) REFERENCES vehicle(id),
    CONSTRAINT fnol_fnol_state_check CHECK ((fnol_state)::text = ANY ((ARRAY['DRAFT'::character varying, 'SUBMITTED'::character varying, 'ENRICHING'::character varying, 'VALIDATED'::character varying, 'REJECTED'::character varying])::text[])),
    CONSTRAINT fnol_severity_check CHECK ((severity)::text = ANY ((ARRAY['High'::character varying, 'Medium'::character varying, 'Low'::character varying])::text[]))
);
CREATE UNIQUE INDEX fnol_index_addr_loc_id ON public.fnol USING btree (accident_location_id);




-- Generated by the database client.
CREATE TABLE fnol_detail(
    id SERIAL NOT NULL,
    additional_notes varchar(255),
    other_party_involved varchar(255),
    supporting_document_url varchar(255),
    witness_name varchar(255),
    witness_phone varchar(255),
    fnol_id bigint,
    PRIMARY KEY(id),
    CONSTRAINT fkkl3un62l64yk55lrgjvct5rgb FOREIGN key(fnol_id) REFERENCES fnol(id)
);
CREATE UNIQUE INDEX fnoldetail_index_fnol_unique ON public.fnol_detail USING btree (fnol_id);



-- Generated by the database client.
CREATE TABLE insured(
    id SERIAL NOT NULL,
    address_line1 varchar(255),
    address_line2 varchar(255),
    city varchar(255),
    country varchar(255),
    created_at date,
    dob date,
    driver_license_no varchar(255),
    email varchar(255),
    first_name varchar(255),
    gender varchar(255),
    last_name varchar(255),
    license_expiry_date date,
    license_issue_date date,
    marital_status varchar(255),
    national_id varchar(255),
    occupation varchar(255),
    passport_number varchar(255),
    phone_number varchar(255),
    postal_code varchar(255),
    province varchar(255),
    updated_at date,
    years_driving integer NOT NULL,
    address_id bigint,
    PRIMARY KEY(id),
    CONSTRAINT fk3wlh6im4u7088k8egehqp6qu0 FOREIGN key(address_id) REFERENCES address(id)
);
CREATE UNIQUE INDEX insured_index_addressid ON public.insured USING btree (address_id);




-- Generated by the database client.
CREATE TABLE policy(
    id SERIAL NOT NULL,
    coverage_type varchar(255),
    end_date date,
    lob varchar(255),
    policy_number varchar(255),
    policy_status varchar(255),
    policy_type varchar(255),
    start_date date,
    insured_id bigint,
    vehicle_id bigint,
    PRIMARY KEY(id),
    CONSTRAINT fkrq3pyxu9yi9hiypvvwqo9snql FOREIGN key(insured_id) REFERENCES insured(id),
    CONSTRAINT fke9xowreu2268itetl73mmii8 FOREIGN key(vehicle_id) REFERENCES vehicle(id)
);
CREATE UNIQUE INDEX policy_index_vehicleid ON public.policy USING btree (vehicle_id);




-- Generated by the database client.
CREATE TABLE surveyor(
    id SERIAL NOT NULL,
    active_jobs_count integer NOT NULL,
    app_version varchar(255),
    capacity_per_day varchar(255),
    city varchar(255),
    country varchar(255),
    created_at date,
    current_lat double precision,
    current_lng double precision,
    email varchar(255),
    internal boolean NOT NULL,
    name varchar(255),
    phone_number varchar(255),
    province varchar(255),
    rating_avg integer NOT NULL,
    skills varchar(255),
    status varchar(255),
    surveyor_job_status varchar(255),
    updated_at date,
    assigned_claim_id bigint,
    PRIMARY KEY(id),
    CONSTRAINT fkpi1u71aufw9hphhwwec450mxy FOREIGN key(assigned_claim_id) REFERENCES claim(id),
    CONSTRAINT surveyor_status_check CHECK ((status)::text = ANY ((ARRAY['ASSIGNED'::character varying, 'AVAILABLE'::character varying, 'ON_SITE'::character varying, 'INSPECTION_DONE'::character varying, 'UNAVAILABLE'::character varying])::text[])),
    CONSTRAINT surveyor_surveyor_job_status_check CHECK ((surveyor_job_status)::text = ANY ((ARRAY['Accepted'::character varying, 'Working'::character varying, 'Pending'::character varying, 'Closed'::character varying, 'On_The_Way'::character varying])::text[]))
);




-- Generated by the database client.
CREATE TABLE vehicle(
    id SERIAL NOT NULL,
    body_type varchar(255),
    color varchar(255),
    created_at date,
    engine_no varchar(255),
    fuel_type varchar(255),
    make varchar(255),
    model varchar(255),
    owner_contact varchar(255),
    owner_name varchar(255),
    registration_number varchar(255),
    registration_state varchar(255),
    updated_at date,
    usage_type varchar(255),
    vin varchar(255),
    year integer,
    PRIMARY KEY(id)
);










